**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [5]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [98]:
null_vector = np.nan * np.empty(10)
null_vector[4] = 1
null_vector

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [111]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print(np.random.random((a,b)))        

Enter first number:  4
Enter second number:  5


[[0.96858462 0.71216901 0.52934764 0.28511182 0.21623394]
 [0.93952859 0.28982779 0.48754301 0.1883313  0.01070952]
 [0.26835102 0.36346582 0.54919092 0.39398264 0.77607317]
 [0.74933677 0.92179589 0.92274068 0.31976924 0.59619953]]


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [124]:
def borderarray(a,b):
    x = np.ones((a,b), dtype=int)
    x[1:-1,1:-1] = 0
    return x

borderarray(4,5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [131]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [142]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [157]:
z = np.zeros((5,5))
z += np.arange(0,5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [174]:
a = np.random.randint(1,100, (10,2))
p = np.array([2,3])
print(a)
distance = np.sqrt(np.sum((a-p) ** 2, axis=1)).astype(int)
distance

[[12 85]
 [ 5 46]
 [69 62]
 [39 97]
 [72 95]
 [49 13]
 [89 93]
 [35 44]
 [20 78]
 [22 38]]


array([ 82,  43,  89, 101, 115,  48, 125,  52,  77,  40])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [177]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [191]:
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

 5 6 8


array([8., 6., 5.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [197]:
a = np.array([1,2])
print(f"elements_count: {a.size}")

elements_count: 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [202]:
def softmax(z):
    # Check if input is a NumPy array
    if not isinstance(z, np.ndarray):
        raise TypeError("Input must be a NumPy array")

    # Check if input is 1D
    if z.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array")

    # Numerical stability: subtract max value
    z_exp = np.exp(z - np.max(z))
    softmax_values = z_exp / np.sum(z_exp)

    return softmax_values

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [218]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Required numpy array.")
    return np.vstack(args)



In [232]:
a= np.arange(10).reshape(2,-1)
b= np.repeat(1,10).reshape(2,-1)
c= np.random.random((2,5))
vertical_stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.3214029 , 0.75043854, 0.03248226, 0.64311305, 0.72824618],
       [0.42890228, 0.81275656, 0.93293742, 0.72687635, 0.98908125]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [17]:
def date_array(start: str, end: str):
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both inputs must be strings")

    return np.arange(
        np.datetime64(start),
        np.datetime64(end) + np.timedelta64(1, 'D'),
        dtype='datetime64[D]'
    )

date_array(start = '2022-12-01', end = '2022-12-06')

array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06'], dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [30]:
x = np.random.random((5,4))
x - x.mean(axis= 1, keepdims= True)

array([[-0.06714135, -0.14057276,  0.10272534,  0.10498877],
       [-0.03410484, -0.15372549, -0.06022598,  0.24805631],
       [ 0.59322313, -0.37935307,  0.01956706, -0.23343712],
       [-0.03085174,  0.16842229,  0.02908953, -0.16666008],
       [ 0.00393707,  0.12762422,  0.16438326, -0.29594455]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [39]:
a = np.arange(9).reshape(3,3)
a[:, [0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [56]:
a = np.arange(10)
a[a % 2 != 0] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [65]:
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
res = np.maximum(a,b)
res

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [69]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[5706, 7636, 8841, 4253, 5251],
       [4998, 8273, 4086, 3629, 2798],
       [8264, 4740,  914, 8101, 4262],
       [8390, 8146, 8844, 4615,  240],
       [3286, 5432, 4983, 7262, 1367],
       [5894, 7951, 1205, 6064, 1388],
       [8385, 4157, 7151, 1106, 2357],
       [1616, 9791,   43, 8907, 7071]])

In [71]:
arr1[:,::2]

array([[5706, 8841, 5251],
       [4998, 4086, 2798],
       [8264,  914, 4262],
       [8390, 8844,  240],
       [3286, 4983, 1367],
       [5894, 1205, 1388],
       [8385, 7151, 2357],
       [1616,   43, 7071]])

In [75]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.58093968, 0.77892901, 0.90254411, 0.43188346, 0.53426344],
       [0.5083094 , 0.84427575, 0.41475174, 0.36787033, 0.28262208],
       [0.84335248, 0.48184243, 0.08935166, 0.8266311 , 0.43280673],
       [0.85627821, 0.83124744, 0.90285187, 0.46901929, 0.02020927],
       [0.33268363, 0.55283135, 0.50677062, 0.74056217, 0.13582273],
       [0.60022569, 0.81124333, 0.11920394, 0.61766516, 0.13797702],
       [0.85576529, 0.42203529, 0.72917522, 0.10904801, 0.23738203],
       [0.16136643, 1.        , 0.        , 0.90931473, 0.7209684 ]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [86]:
def nthmax(arr, n):
    if n > len(arr):
        raise IndexError("n is way out of limit.")
    arr.sort()
    return arr[-n]

nthmax(arr=np.array([12,34,40,7,1,0]), n=1)

40

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [95]:
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])